CREATE TABLE Developers (
    DevId INT IDENTITY(1,1) PRIMARY KEY,
    Username VARCHAR(50) UNIQUE NOT NULL ,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE ScriptType (
    TypeId INT IDENTITY(1,1) PRIMARY KEY,
    TypeName VARCHAR(50) UNIQUE NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Scripts (
    ScriptId INT IDENTITY(1,1) PRIMARY KEY,
    DevId INT NOT NULL FOREIGN KEY REFERENCES Developers(DevId),
    TypeId INT NOT NULL FOREIGN KEY REFERENCES ScriptType(TypeId),
    ScriptName VARCHAR(50) NOT NULL,
    ScriptS3Url VARCHAR(100) UNIQUE NOT NULL,
    ScriptVersion INT NOT NULL DEFAULT 1,
    LastUpdated DATETIME DEFAULT GETDATE(),
    CreatedAt DATETIME DEFAULT GETDATE()
);
